#! /bin/sh

PREREQ=""
DESCRIPTION="Setting up locales..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

conf_file="/root/etc/default/locale"
locale="en_US.UTF-8"

if [ -f "${conf_file}" ]; then
    locale=$(grep -s 'LANG=' ${conf_file} | sed s/'LANG='// | tr -d '"' )
fi

for x in $(cat /proc/cmdline); do
    case $x in
	debian-installer/language=*)
	    language=${x#debian-installer/language=}
	    locale="$(lang2locale "$language")"
	    ;;
	debian-installer/locale=*)
	    locale=${x#debian-installer/locale=}
	    ;;
	locale=*)
	    locale=${x#locale=}
	    ;;
    esac
done

LANG=$(grep "^${locale}" /root/usr/share/i18n/SUPPORTED | grep UTF-8 |sed -e 's, .*,,' -e q)
printf 'LANG="%s"\n' "${LANG}" > ${conf_file}
printf '%s UTF-8\n' "${LANG}" > /root/etc/locale.gen
chroot /root /usr/sbin/locale-gen "${LANG}"

log_end_msg
