#! /bin/sh

if [ -d /root/usr/share/kubuntu-default-settings/ ]; then
    echo "[Event]\nhideRestartNotifier=true" >> /root/usr/share/kubuntu-default-settings/kde-profile/default/share/config/notificationhelper
fi
