#!/bin/sh

PREREQ=""
DESCRIPTION="Enable post startup script..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

setdir="/root/livefs"

if [ -n "$setdir" -a -f $setdir/casper.override.tgz ]; then
  cp $setdir/casper.override.tgz /root
  chroot /root tar -C / -x -z -f /casper.override.tgz
  rm /root/casper.override.tgz
elif [ -n "$setdir" -a -f $setdir/casper.override.tbz ]; then
  cp $setdir/casper.override.tbz /root
  chroot /root tar -C / -x -j -f /casper.override.tbz
  rm /root/casper.override.tbz
elif [ -n "$setdir" -a -d $setdir/casper.override ]; then
  cp -r $setdir/casper.override/* /root
fi

if [ -n "$setdir" -a -f $setdir/casper.preinit ]; then
  cp $setdir/casper.preinit /root/etc/init.d/casper-preinitialize
  chroot /root chown 0:0 /etc/init.d/casper-preinitialize
  chroot /root chmod 755 /etc/init.d/casper-preinitialize
  mount -n -o bind /sys /root/sys
  mount -n -o bind /proc /root/proc
  mount -n -o bind /dev /root/dev
  chroot /root /etc/init.d/casper-preinitialize
  umount /root/sys
  umount /root/proc
  umount /root/dev
fi

if [ -n "$setdir" -a -f $setdir/casper.init ]; then
  cp $setdir/casper.init /root/etc/init.d/casper-initialize
  chroot /root chown 0:0 /etc/init.d/casper-initialize
  chroot /root chmod 755 /etc/init.d/casper-initialize
  chroot /root update-rc.d casper-initialize start 00 2 3 4 5 .
fi

if [ -n "$setdir" -a -f $setdir/casper.sh ]; then
  cp $setdir/casper.sh /root/etc/init.d/casper-startup
  chroot /root chown 0:0 /etc/init.d/casper-startup
  chroot /root chmod 755 /etc/init.d/casper-startup
  chroot /root update-rc.d casper-startup start 99 2 3 4 5 .
fi

log_end_msg
