#!/bin/sh

OPTION=FRAMEBUFFER
PREREQ="udev"
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

[ -x /sbin/brltty ] || exit 0

# Start BRLTTY
if [ -r /etc/brltty.conf ]; then
  /sbin/brltty -eqN 2>/dev/tty2
fi
