#!/bin/sh

PREREQ="udev"

prereqs() {
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /scripts/functions

[ -x /sbin/dropbear ] || exit 0

log_begin_msg "Starting dropbear"

. /conf/initramfs.conf

configure_networking &

mkdir -p /var/run
/sbin/dropbear

