#!/bin/bash
for service in \
  apache2 \
  apt-cacher-ng \
  atftpd \
  bluetooth \
  docker \
  docker.io \
  dovecot \
  exim4 \
  fcgiwrap \
  gdm \
  greylist \
  inetd \
  inetutils-inetd \
  isc-dhcp-server \
  isc-dhcp-server6 \
  kdm \
  lightdm \
  memcached \
  mysql \
  nbd-server \
  network-manager \
  nginx \
  nmbd \
  ntp \
  openvpn \
  postfix \
  postgres \
  postgresql \
  reload-smbd \
  rlinetd \
  samba-ad-dc \
  saned \
  smbd \
  spamassassin \
  tinyproxy \
  virtualbox \
  virtualbox-guest-utils \
  vmware \
  vmware-USBArbitrator \
  vsftpd \
  winbind \
; do
    update-rc.d -f "${service}" disable
    if [ -e "/etc/init/${service}.conf" ]; then
        echo "manual" > "/etc/init/${service}.override"
    fi
done
