#!/bin/bash
OFFICE=$(dirname "$(readlink -f "$(which "$0")")")
pushd "${OFFICE}"
source settings.sh

CUDA_LINK="http://developer.download.nvidia.com/compute/cuda/6_5/rel/installers/cuda_6.5.14_linux_64.run"

wget -c -t 10 "${CUDA_LINK}" -O /tmp/cuda.run &&
mv /tmp/cuda.run . &&
chmod 755 cuda.run &&
./cuda.run -toolkit -override -silent &&
./cuda.run -samples -override -silent &&
#make -C /usr/local/cuda/samples -j 16 &&
exit 0

exit 1
