from django.http import HttpResponse
from satori.core.models import *

def create(request):
    ProblemMapping.objects.all().delete()
    Problem.objects.all().delete()
    Contestant.objects.all().delete()
    Contest.objects.all().delete()
    User.objects.all().delete()
    MessageGlobal.objects.all().delete()
    MessageContest.objects.all().delete()
    paladin = User(fullname='Lech Duraj', login='paladin')
    paladin.save()
    User(fullname='Edgsger W. Dijkstra', login = 'dijkstra').save()
    c2 = Contest(name = 'Kontest prywatny', joining = 'Private')
    c3 = Contest(name = 'Kontest moderowany', joining = 'Moderated')
    c4 = Contest(name = 'Kontest publiczny', joining = 'Public')
    c2.save()
    c3.save()
    c4.save()
    Contestant(user = paladin, contest = c2, accepted = True).save()
    Contestant(user = paladin, contest = c3, accepted = True).save()
    Contestant(user = paladin, contest = c4, accepted = True).save()
    p1 = Problem(name = "SORT", description = "Zadanie o sortowaniu")
    p2 = Problem(name = "COW", description = "Zadanie o krowie")
    p3 = Problem(name = "WUWU", description = "Zadanie o wuwuzeli")
    p1.save()
    p2.save()
    p3.save()
    ProblemMapping(problem = p1, contest = c4, code = "A", title = "Harry Potter i sortownia smieci").save()
    ProblemMapping(problem = p2, contest = c4, code = "B", title = "Harry Potter i krowa z Albanii").save()
    ProblemMapping(problem = p3, contest = c4, code = "C", title = "Harry Potter i wuwuzele").save()
    MessageGlobal(topic = "Wiadomosc pierwsza", content = "BZZZZZ!", mainscreenonly = True).save()
    MessageGlobal(topic = "Wiadomosc systemowa", content = "Oglaszamy, ze za 5 minuBZZZZZ!", mainscreenonly = False).save()
    MessageContest(topic = "Wiadomosc powitalna", content = "Publiczne BZZZZZ!", contest = c4).save()
    return HttpResponse('OK!')
