#! /bin/sh

PREREQ=""

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if [ -e /root/etc/default/locale ]; then
    grep_file=/root/etc/default/locale
elif [ -e /root/etc/environment ]; then # Old locales policy
    grep_file=/root/etc/environment
fi

timezone="Etc/UTC"
timeserver=""

if [ -n "${grep_file}" ]; then
    # use rootfs configured locale
    timezone=$(grep -s 'TZ=' ${grep_file} | sed s/'TZ='// | tr -d '"' )
fi

for x in $(cat /proc/cmdline); do
    case $x in
	timeserver=*)
	    timeserver=${x#timeserver=}
	    ;;
	timezone=*)
	    timezone=${x#timezone=}
	    ;;
    esac
done

cp -f /root/usr/share/zoneinfo/${timezone} /root/etc/localtime
echo "${timezone}" > /root/etc/timezone

if [ -n "${timeserver}" ]; then
  sed -i -e "s|^ *server .*$|server $timeserver|" /root/etc/ntp.conf
  mount -n -o bind /sys /root/sys
  mount -n -o bind /proc /root/proc
  mount -n -o bind /dev /root/dev
  chroot /root ntpdate $timeserver
  chroot /root hwclock --utc --systohc
  umount /root/sys
  umount /root/proc
  umount /root/dev
fi
