#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring screensaver..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

gnome_screensaver_version=$(chroot /root dpkg-query -W --showformat='${Version}' gnome-screensaver 2>/dev/null) || gnome_screensaver_version=""
if [ -n "$gnome_screensaver_version" -a -n "${USERNAME}" ]; then
    chroot /root sudo -u "$USERNAME" gsettings set org.gnome.desktop.screensaver lock-enabled  false
fi

if [ -d /root/usr/share/kubuntu-default-settings/kde-profile/default/share/config ]; then
    printf "[ScreenSaver]\nLock=false\n" >> /root/usr/share/kubuntu-default-settings/kde-profile/default/share/config/kdesktoprc
fi

log_end_msg
