#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling user menu..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

indicator_session_version=$(chroot /root dpkg-query -W --showformat='${Version}' indicator-session 2>/dev/null) || indicator_session_version=""
if [ -n "$indicator_session_version=" ]; then
    chroot /root sudo -u "$USERNAME" gsettings set com.canonical.indicator.session user-show-menu  false
fi

log_end_msg
