#!/bin/sh
# If you are looking to change accessibility profile settings, plesae look in
# bin/casper-a11y-enable.

PREREQ=""
DESCRIPTION="Configuring accessibility options..."

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
	prereqs)
		prereqs
	       exit 0
	       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

for x in $(cat /proc/cmdline); do
	case $x in
		# Lesser Visual Impairment
		access=v1)
			/root/usr/bin/casper-a11y-enable -initramfs -user="$USERNAME" -chroot=/root -script high-contrast
                        ;;
		# Moderate Visual Impairment
		access=v2)
			/root/usr/bin/casper-a11y-enable -initramfs -user="$USERNAME" -chroot=/root -script magnifier
                        ;;
		# Blindness
		access=v3)
			/root/usr/bin/casper-a11y-enable -initramfs -user="$USERNAME" -chroot=/root -script blindness
                        ;;
		# Braille
		braille=ask)
			/root/usr/bin/casper-a11y-enable -initramfs -user="$USERNAME" -chroot=/root -script braille
                        ;;
		# Minor Motor Difficulties
		access=m1)
			/root/usr/bin/casper-a11y-enable -initramfs -user="$USERNAME" -chroot=/root -script keyboard-modifiers
                        ;;
		# Motor Difficulties - pointing devices
		access=m2)
			/root/usr/bin/casper-a11y-enable -initramfs -user="$USERNAME" -chroot=/root -script onscreen-keyboard
                        ;;
		esac
done
log_end_msg
