#!/bin/sh

# init-premount script for mdadm.

PREREQS="udev"

prereqs()
{
	echo $PREREQS
}

[ "$1" = "prereqs" ] || . /scripts/mdadm-functions

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
mountfail)
	mountroot_fail
	exit $?
	;;
esac

. /scripts/functions

add_mountroot_fail_hook "10-mdadm"

exit 0
 
