#!/usr/bin/env python2.6

import os
import sys

def lookup(dir):
    init = os.path.join(dir, '__init__.py')
    if os.path.exists(init):
        yield dir
        return
    for file in os.listdir(dir):
        file = os.path.join(dir, file)
        if os.path.isdir(file):
            for item in lookup(file):
                yield item
        elif file.endswith('.py'):
            yield file

config = os.path.join(os.path.dirname(sys.argv[0]), 'pylint.conf')
options = ['--rcfile=' + config]
files = []
for arg in sys.argv[1:]:
    if arg.endswith('.py'):
        files.append(arg)
    else:
        options.append(arg)
if not files:
    files = [f for f in lookup('satori')]

os.execvp('pylint', ['pylint'] + options + files)
