#!/bin/env python2.6

import os
import sys

def lookup(dir):
    for file in os.listdir(dir):
        file = os.path.join(dir, file)
        if os.path.isdir(file):
            for item in lookup(file):
                yield item
        elif file.endswith('tests.py'):
            yield file

options = []
modules = []
for arg in sys.argv[1:]:
    if arg.endswith('.py'):
        modules.append(arg)
    else:
        options.append(arg)
if not modules:
    modules = [f.replace('/', '.') for f in lookup('satori')]

status = 0
for module in modules:
    status |= os.spawnvp(os.P_WAIT, 'pytest', ['pytest'] + options + [module])
sys.exit(status)