#!/bin/bash
OFFICE=$(dirname "$(readlink -f "$(which "$0")")")
pushd "${OFFICE}/kernel"
./make.sh &&
cp current-generic/vmlinuz current-generic/initrd.cpio.lzma current-generic/modules.tar.bz2 /root &&
exit 0
popd
exit 1
