#!/bin/sh

PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

# find total amount of available ram
TOTAL_RAM=$( grep MemTotal /proc/meminfo |tr -d ': [A-Z][a-z]')

# Do not use compcache on the liveCD if we have more than 512M
if [ "${BOOT}" = "casper" ]; then
    if [ "${TOTAL_RAM}" -gt 524288 ]; then
        exit 0
    fi
fi

for x in $(cat /proc/cmdline); do
        case ${x} in
        nocompcache)
                exit 0
        ;;
        esac
done

modprobe -q --ignore-install zram
